<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use function Ramsey\Uuid\v1;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        DB::table('products')->truncate();
        DB::table('products')->insert([
            [
                'id'=>1,
                'name'=>'Rau Cải Ngọt',
                'gardenname'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>23.100,
                'weight'=>'1 kg',
                'thumbnail'=>'https://orfarm.com.vn/images/products/2020/07/11/original/27_f102291_rau_muong_3962a35b44254dcda56c59ebc01f7594_large_1594437180.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>2,
                'name'=>'Rau Mồng Tơi',
                'gardenname'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>28.200,
                'weight'=>'1 kg',
                'thumbnail'=>'https://image.vtc.vn/files/ctv.congnghe4/2018/04/01/1-1421474.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>3,
                'name'=>'Su Su',
                'gardenname'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>16.400,
                'weight'=>'1 kg',
                'thumbnail'=>'https://minhcaumart.vn/media/com_eshop/products/2900053.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>4,
                'name'=>'Bí Đỏ',
                'gardenname'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>11.900,
                'weight'=>'1 kg',
                'thumbnail'=>'https://vinmec-prod.s3.amazonaws.com/images/20200710_144301_558174_bi-ngo-1.max-800x800.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id'=>5,
                'name'=>'Khoai Tây',
                'gardenname'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>25.000,
                'weight'=>'1 kg',
                'thumbnail'=>'https://leep.imgix.net/2021/01/Ham-luong-dinh-duong-co-trong-khoai-tay.jpg?auto=compress&fm=pjpg&ixlib=php-1.2.1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>6,
                'name'=>'Măng',
                'gardenname'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>28.200,
                'weight'=>'1 kg',
                'thumbnail'=>'https://khaitamgroup.com/wp-content/uploads/2019/12/m%C4%83ng-n%E1%BB%A9a-t%C6%B0%C6%A1i.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>7,
                'name'=>'Bắp Cải',
                'gardenname'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>25.000,
                'weight'=>'1 kg',
                'thumbnail'=>'https://mamnonhoami.edu.vn/wp-content/uploads/2015/03/bap-cai-xanh-tho-thieu-nhi-1024x1024.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>8,
                'name'=>'Rau Muống',
                'gardenname'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>33.900 ,
                'weight'=>'1 kg',
                'thumbnail'=>'https://minhcaumart.vn/media/com_eshop/products/RAUMUONG.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>9,
                'name'=>'Khoai Lang',
                'gardenname'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>28.500,
                'weight'=>'1 kg',
                'thumbnail'=>'https://i1-giadinh.vnecdn.net/2013/12/21/anh-9211-1387615838.jpg?w=680&h=0&q=100&dpr=1&fit=crop&s=aH8uqPtb6sC-q8TJWLB0dA',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>10,
                'name'=>'Rau Mùi',
                'gardenname'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>42.900,
                'weight'=>'1 kg',
                'thumbnail'=>'https://bizweb.dktcdn.net/100/355/169/articles/20159162228314.jpg?v=1557464417160',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>11,
                'name'=>'Dưa Chuột',
                'gardenname'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>38.300,
                'weight'=>'1 kg',
                'thumbnail'=>'https://media-cdn.laodong.vn/storage/newsportal/Uploaded/ctvsuckhoe/2016_08_23/0_OMUN.jpg?w=888&h=592&crop=auto&scale=both',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>12,
                'name'=>'Bí Đao',
                'gardenname'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>20.300,
                'weight'=>'1 kg',
                'thumbnail'=>'https://khuyennongtphcm.com/wp-content/uploads/2020/09/bi-xanh.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>13,
                'name'=>'Rau Cải Thìa',
                'gardenname'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>39.400,
                'weight'=>'1 kg',
                'thumbnail'=>'https://admin.nongsandungha.com/wp-content/uploads/2021/06/cai-chip-min.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>14,
                'name'=>'Cam',
                'gardenname'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>43.900,
                'weight'=>'1 kg',
                'thumbnail'=>'https://cdnfiles.bizgo.vn/401/images/2017/08/small.cam-sanh-canada1.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>15,
                'name'=>'Chuối',
                'gardenname'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>19.500,
                'weight'=>'1 kg',
                'thumbnail'=>'https://photo-cms-plo.zadn.vn/w800/Uploaded/2021/ymzmf/2018_01_17/chuoi-xanh_lqnu_thumb.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>16,
                'name'=>'Khế',
                'gardenname'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>62.500,
                'weight'=>'1 kg',
                'thumbnail'=>'https://vietblend.vn/wp-content/uploads/2018/12/qua-khe.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>17,
                'name'=>'Đào',
                'gardenname'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>35.000,
                'weight'=>'1 kg',
                'thumbnail'=>'https://suckhoedoisong.qltns.mediacdn.vn/Images/duylinh/2020/05/14/dao_2_resize.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>18,
                'name'=>'Tỏi',
                'gardenname'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>32.000,
                'weight'=>'1 kg',
                'thumbnail'=>'https://login.medlatec.vn//ImagePath/images/20200602/20200602_cong-dung-cua-toi-1.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>19,
                'name'=>'Me',
                'gardenname'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>53.900,
                'weight'=>'1 kg',
                'thumbnail'=>'https://baogialai.com.vn/dataimages/201912/original/images2835501_1qua_me_zxjy.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>20,
                'name'=>'Bưởi',
                'gardenname'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>60.000,
                'weight'=>'1 kg',
                'thumbnail'=>'https://lh6.googleusercontent.com/-mg0w7L62lOqLV3k3IO5lNSlQYrbRRZK9x6xPcbXNjQSnwugGnrHqLh9sqLJKrx01LOBWc8eWlENBsQ_zxVPBsvqOnZPFYzDnNiH2UJE-dztAzEasVhgphYPBjX_DBVvVWljCvo',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>21,
                'name'=>'Atiso',
                'gardenname'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>80.000,
                'weight'=>'1 kg',
                'thumbnail'=>'https://suckhoedoisong.qltns.mediacdn.vn/Images/thanhloan/2016/05/02/hoa-atiso.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>22,
                'name'=>'Cần Tây',
                'gardenname'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>35.000,
                'weight'=>'1 kg',
                'thumbnail'=>'https://www.minhcaumart.vn/media/com_eshop/products/2900531.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>23,
                'name'=>'Thì Là',
                'gardenname'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>80.000,
                'weight'=>'1 kg',
                'thumbnail'=>'https://minhcaumart.vn/media/com_eshop/products/Rau-Thi-La.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>24,
                'name'=>'Nấm',
                'gardenname'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>130.000,
                'weight'=>'1 kg',
                'thumbnail'=>'http://rica.vn/datafiles/28436/upload/images/news/nam-bao-ngu-nam-so-1.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>25,
                'name'=>'Ớt Chuông',
                'gardenname'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>61.000,
                'weight'=>'1 kg',
                'thumbnail'=>'https://cf.shopee.vn/file/769fd1c94cb710e05dc149ab4aaf3bf3',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>26,
                'name'=>'Ớt Cay',
                'gardenname'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>80.000,
                'weight'=>'1 kg',
                'thumbnail'=>'https://hongngochospital.vn/wp-content/uploads/2013/11/doi-tuong-khong-nen-an-ot-1.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>27,
                'name'=>'Cải Xoong',
                'gardenname'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>40.000,
                'weight'=>'1 kg',
                'thumbnail'=>'https://cf.shopee.vn/file/a725df7dfea3fb8ba285f5bb7bcbdd2f',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>28,
                'name'=>'Khoai Mỡ',
                'gardenname'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>47.000,
                'weight'=>'1 kg',
                'thumbnail'=>'https://cdn.tgdd.vn/2020/10/content/2-800x604.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>29,
                'name'=>'Sắn',
                'gardenname'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>20.000,
                'weight'=>'1 kg',
                'thumbnail'=>'https://photo-cms-plo.zadn.vn/w800/Uploaded/2021/xqeioxmrke/2020_05_06/tacdungcuacukhoaimi_yevf.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>30,
                'name'=>'Bạc Hà',
                'gardenname'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>10.000,
                'weight'=>'1 kg',
                'thumbnail'=>'http://hn.check.net.vn/data/product/mainimages/original/product12237.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>31,
                'name'=>'Củ Sen',
                'gardenname'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>50.000,
                'weight'=>'1 kg',
                'thumbnail'=>'https://suckhoedoisong.qltns.mediacdn.vn/Images/bichvan/2019/07/13/cu_sen.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>32,
                'name'=>'Nghệ',
                'gardenname'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>600.000,
                'weight'=>'1 kg',
                'thumbnail'=>'https://niceshop.vn/wp-content/uploads/2020/02/tinh-b%E1%BB%99t-ngh%E1%BB%87.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>33,
                'name'=>'Su Hào',
                'gardenname'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>10.000,
                'weight'=>'1 kg',
                'thumbnail'=>'https://salt.tikicdn.com/cache/w1200/ts/product/22/c5/8b/bcf9a3aba82595cf04e05e22346e0e1c.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>34,
                'name'=>'Rau Răm',
                'gardenname'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>15.000,
                'weight'=>'1 kg',
                'thumbnail'=>'https://thuocdantoc.vn/wp-content/uploads/2020/09/rau-ram-chua-viem-da-co-dia2.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>35,
                'name'=>'Rau Má',
                'gardenname'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>35.000,
                'weight'=>'1 kg',
                'thumbnail'=>'https://i2.wp.com/thucphamtantai.com/wp-content/uploads/2019/10/rau-ma-600x740.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>36,
                'name'=>'Cải Đắng',
                'gardenname'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>13.000,
                'weight'=>'1 kg',
                'thumbnail'=>'https://i0.wp.com/thucphamtantai.com/wp-content/uploads/2019/10/cai-be-xanh.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>37,
                'name'=>'Rong Biển',
                'gardenname'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>100.000,
                'weight'=>'1 kg',
                'thumbnail'=>'https://www.havamall.com/wp-content/uploads/2019/12/image_2019_12_09T09_35_47_632Z.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>38,
                'name'=>'Đậu Đũa',
                'gardenname'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>40.000,
                'weight'=>'1 kg',
                'thumbnail'=>'https://csfood.vn/wp-content/uploads/2020/04/%C4%90%E1%BA%ADu-%C4%90%C5%A9a-VietRAT-T%C3%BAi-1kg.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>39,
                'name'=>'Củ Hẹ',
                'gardenname'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>50.000,
                'weight'=>'1 kg',
                'thumbnail'=>'https://www.collinsdictionary.com/images/full/shallot_6435766.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>40,
                'name'=>'Rau Nhút',
                'gardenname'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>35.000,
                'weight'=>'1 kg',
                'thumbnail'=>'https://cdn.myshoptet.com/usr/www.vegandfood.com/user/shop/big/2554_water-mimosa.png?60fece6c',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>41,
                'name'=>'Mướp',
                'gardenname'=>'Nông trại hữu cơ Viễn Phú',
                'price'=>27.500,
                'weight'=>'1 kg',
                'thumbnail'=>'https://csfood.vn/wp-content/uploads/2018/03/M%C6%B0%E1%BB%9Bp-Vietrat....png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>42,
                'name'=>'Củ Riềng',
                'gardenname'=>'Nông trại hữu cơ Viễn Phú',
                'price'=>15.000,
                'weight'=>'1 kg',
                'thumbnail'=>'https://m.soibien.vn/media/img/product/365/03/curieng_9471588761734.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>43,
                'name'=>'Mía',
                'gardenname'=>'Nông trại hữu cơ Viễn Phú',
                'price'=>1.000,
                'weight'=>'1 kg',
                'thumbnail'=>'https://www.mabu.vn/wp-content/uploads/2016/08/cay-mia.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>44,
                'name'=>'Đậu Bắp',
                'gardenname'=>'Nông trại hữu cơ Viễn Phú',
                'price'=>20.000,
                'weight'=>'1 kg',
                'thumbnail'=>'https://salt.tikicdn.com/cache/w1200/ts/product/7b/cb/5f/9834fbe63f28655489f7e2aef21e9ccc.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>45,
                'name'=>'Tía Tô',
                'gardenname'=>'Nông trại hữu cơ Viễn Phú',
                'price'=>50.000,
                'weight'=>'1 kg',
                'thumbnail'=>'https://dungcunongnghiep.vn/files/sanpham/855/1/jpg/tia-to-la-do.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>46,
                'name'=>'Quất',
                'gardenname'=>'Nông trại hữu cơ Viễn Phú',
                'price'=>35.000,
                'weight'=>'1 kg',
                'thumbnail'=>'https://cdn.tgdd.vn/Products/Images/8786/232812/bhx/tac-trai-tui-300g-202012282304414517.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>47,
                'name'=>'Mít',
                'gardenname'=>'Nông trại hữu cơ Viễn Phú',
                'price'=>30.000,
                'weight'=>'1 kg',
                'thumbnail'=>'https://sanvatphuongnam.vn/image/cache/catalog/products/tien-giang/mit-thai-cai-be-2-800x800.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>48,
                'name'=>'Sầu Riêng',
                'gardenname'=>'Nông trại hữu cơ Viễn Phú',
                'price'=>65.000,
                'weight'=>'1 kg',
                'thumbnail'=>'https://lanhtaychan.com/sau-rieng-mui.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>49,
                'name'=>'Chanh Vàng',
                'gardenname'=>'Nông trại hữu cơ Viễn Phú',
                'price'=>60.000,
                'weight'=>'1 kg',
                'thumbnail'=>'https://bizweb.dktcdn.net/thumb/1024x1024/100/372/252/products/chanh-vang.jpg?v=1594033185967',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

        ]);
    }
}




