<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        DB::table('products')->truncate();
        DB::table('products')->insert([
            [
                'id'=>1,
                'name'=>'Rau Cải Ngọt',
                'gardenName'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>'23.100 đồng',
                'weight'=>'1 kg',
                'category'=>'rau',
                'thumbnail'=>'https://orfarm.com.vn/images/products/2020/07/11/original/27_f102291_rau_muong_3962a35b44254dcda56c59ebc01f7594_large_1594437180.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>2,
                'name'=>'Rau Mồng Tơi',
                'gardenName'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>'28.200 đồng',
                'weight'=>'1 kg',
                'category'=>'rau',
                'thumbnail'=>'https://image.vtc.vn/files/ctv.congnghe4/2018/04/01/1-1421474.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>3,
                'name'=>'Su Su',
                'gardenName'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>'16.400 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://minhcaumart.vn/media/com_eshop/products/2900053.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>4,
                'name'=>'Bí Đỏ',
                'gardenName'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>'11.900 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'http://dermacare.vn/wp-content/uploads/2021/06/6748efdcfef76c50b0a381df7829083f.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id'=>5,
                'name'=>'Khoai Tây',
                'gardenName'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>'25.000 đồng',
                'weight'=>'1 kg',
                'category'=>'củ',
                'thumbnail'=>'https://leep.imgix.net/2021/01/Ham-luong-dinh-duong-co-trong-khoai-tay.jpg?auto=compress&fm=pjpg&ixlib=php-1.2.1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>6,
                'name'=>'Măng',
                'gardenName'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>'28.200 đồng',
                'weight'=>'1 kg',
                'category'=>'rau',
                'thumbnail'=>'https://thucphamdongxanh.com/wp-content/uploads/2019/09/19f7__mang-vang.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>7,
                'name'=>'Bắp Cải',
                'gardenName'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>'25.000 đồng',
                'weight'=>'1 kg',
                'category'=>'rau',
                'thumbnail'=>'https://mamnonhoami.edu.vn/wp-content/uploads/2015/03/bap-cai-xanh-tho-thieu-nhi-1024x1024.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>8,
                'name'=>'Rau Muống',
                'gardenName'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>'33.900 đồng',
                'weight'=>'1 kg',
                'category'=>'rau',
                'thumbnail'=>'https://minhcaumart.vn/media/com_eshop/products/RAUMUONG.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>9,
                'name'=>'Khoai Lang',
                'gardenName'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>'28.500 đồng',
                'weight'=>'1 kg',
                'category'=>'củ',
                'thumbnail'=>'https://vuacua.vn/storage/media/jqyp6YyCAIiJkSb1wwOp6oQJ4iqzS0007gPRgLib.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>10,
                'name'=>'Rau Mùi',
                'gardenName'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>'42.900 đồng',
                'weight'=>'1 kg',
                'category'=>'rau',
                'thumbnail'=>'http://st.suckhoegiadinh.com.vn/staticFile/Subject/2019/09/25/rau-mui-dung-ha_25230379.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>11,
                'name'=>'Dưa Chuột',
                'gardenName'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>'38.300 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://media-cdn.laodong.vn/storage/newsportal/Uploaded/ctvsuckhoe/2016_08_23/0_OMUN.jpg?w=888&h=592&crop=auto&scale=both',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>12,
                'name'=>'Bí Đao',
                'gardenName'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>'20.300 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://khuyennongtphcm.com/wp-content/uploads/2020/09/bi-xanh.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>13,
                'name'=>'Rau Cải Thìa',
                'gardenName'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>'39.400 đồng',
                'weight'=>'1 kg',
                'category'=>'rau',
                'thumbnail'=>'https://admin.nongsandungha.com/wp-content/uploads/2021/06/cai-chip-min.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>14,
                'name'=>'Cam',
                'gardenName'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>'43.900 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://cdnfiles.bizgo.vn/401/images/2017/08/small.cam-sanh-canada1.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>15,
                'name'=>'Chuối',
                'gardenName'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>'19.500 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://photo-cms-plo.zadn.vn/w800/Uploaded/2021/ymzmf/2018_01_17/chuoi-xanh_lqnu_thumb.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>16,
                'name'=>'Khế',
                'gardenName'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>'62.500 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://vietblend.vn/wp-content/uploads/2018/12/qua-khe.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>17,
                'name'=>'Đào',
                'gardenName'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>'35.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://suckhoedoisong.qltns.mediacdn.vn/Images/duylinh/2020/05/14/dao_2_resize.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>18,
                'name'=>'Tỏi',
                'gardenName'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>'32.000 đồng',
                'weight'=>'1 kg',
                'category'=>'củ',
                'thumbnail'=>'https://login.medlatec.vn//ImagePath/images/20200602/20200602_cong-dung-cua-toi-1.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>19,
                'name'=>'Me',
                'gardenName'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>'53.900 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://baogialai.com.vn/dataimages/201912/original/images2835501_1qua_me_zxjy.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>20,
                'name'=>'Bưởi',
                'gardenName'=>'Trang trại rau hữu cơ Organik Đà Lạt',
                'price'=>'60.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://lh6.googleusercontent.com/-mg0w7L62lOqLV3k3IO5lNSlQYrbRRZK9x6xPcbXNjQSnwugGnrHqLh9sqLJKrx01LOBWc8eWlENBsQ_zxVPBsvqOnZPFYzDnNiH2UJE-dztAzEasVhgphYPBjX_DBVvVWljCvo',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>21,
                'name'=>'Atiso',
                'gardenName'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>'80.000 đồng',
                'weight'=>'1 kg',
                'category'=>'rau',
                'thumbnail'=>'https://suckhoedoisong.qltns.mediacdn.vn/Images/thanhloan/2016/05/02/hoa-atiso.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>22,
                'name'=>'Cần Tây',
                'gardenName'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>'35.000 đồng',
                'weight'=>'1 kg',
                'category'=>'rau',
                'thumbnail'=>'https://www.minhcaumart.vn/media/com_eshop/products/2900531.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>23,
                'name'=>'Thì Là',
                'gardenName'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>'80.000 đồng',
                'weight'=>'1 kg',
                'category'=>'rau',
                'thumbnail'=>'https://minhcaumart.vn/media/com_eshop/products/Rau-Thi-La.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>24,
                'name'=>'Nấm',
                'gardenName'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>'130.000 đồng',
                'weight'=>'1 kg',
                'category'=>'rau',
                'thumbnail'=>'http://rica.vn/datafiles/28436/upload/images/news/nam-bao-ngu-nam-so-1.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>25,
                'name'=>'Ớt Chuông',
                'gardenName'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>'61.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://cf.shopee.vn/file/769fd1c94cb710e05dc149ab4aaf3bf3',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>26,
                'name'=>'Ớt Cay',
                'gardenName'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>'80.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://hongngochospital.vn/wp-content/uploads/2013/11/doi-tuong-khong-nen-an-ot-1.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>27,
                'name'=>'Cải Xoong',
                'gardenName'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>'40.000 đồng',
                'weight'=>'1 kg',
                'category'=>'rau',
                'thumbnail'=>'https://cf.shopee.vn/file/a725df7dfea3fb8ba285f5bb7bcbdd2f',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>28,
                'name'=>'Khoai Mỡ',
                'gardenName'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>'47.000 đồng',
                'weight'=>'1 kg',
                'category'=>'củ',
                'thumbnail'=>'https://cdn.tgdd.vn/2020/10/content/2-800x604.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>29,
                'name'=>'Sắn',
                'gardenName'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>'20.000 đồng',
                'weight'=>'1 kg',
                'category'=>'củ',
                'thumbnail'=>'https://photo-cms-plo.zadn.vn/w800/Uploaded/2021/xqeioxmrke/2020_05_06/tacdungcuacukhoaimi_yevf.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>30,
                'name'=>'Bạc Hà',
                'gardenName'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>'10.000 đồng',
                'weight'=>'1 kg',
                'category'=>'rau',
                'thumbnail'=>'http://hn.check.net.vn/data/product/mainimages/original/product12237.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>31,
                'name'=>'Củ Sen',
                'gardenName'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>'50.000 đồng',
                'weight'=>'1 kg',
                'category'=>'củ',
                'thumbnail'=>'https://suckhoedoisong.qltns.mediacdn.vn/Images/bichvan/2019/07/13/cu_sen.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>32,
                'name'=>'Nghệ',
                'gardenName'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>'600.000 đồng',
                'weight'=>'1 kg',
                'category'=>'củ',
                'thumbnail'=>'https://niceshop.vn/wp-content/uploads/2020/02/tinh-b%E1%BB%99t-ngh%E1%BB%87.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>33,
                'name'=>'Su Hào',
                'gardenName'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>'10.000 đồng',
                'weight'=>'1 kg',
                'category'=>'củ',
                'thumbnail'=>'https://salt.tikicdn.com/cache/w1200/ts/product/22/c5/8b/bcf9a3aba82595cf04e05e22346e0e1c.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>34,
                'name'=>'Rau Răm',
                'gardenName'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>'15.000 đồng',
                'weight'=>'1 kg',
                'category'=>'rau',
                'thumbnail'=>'https://thuocdantoc.vn/wp-content/uploads/2020/09/rau-ram-chua-viem-da-co-dia2.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>35,
                'name'=>'Rau Má',
                'gardenName'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>'35.000 đồng',
                'weight'=>'1 kg',
                'category'=>'rau',
                'thumbnail'=>'https://i2.wp.com/thucphamtantai.com/wp-content/uploads/2019/10/rau-ma-600x740.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>36,
                'name'=>'Cải Đắng',
                'gardenName'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>'13.000 đồng',
                'weight'=>'1 kg',
                'category'=>'rau',
                'thumbnail'=>'https://i0.wp.com/thucphamtantai.com/wp-content/uploads/2019/10/cai-be-xanh.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>37,
                'name'=>'Rong Biển',
                'gardenName'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>'100.000 đồng',
                'weight'=>'1 kg',
                'category'=>'rau',
                'thumbnail'=>'https://www.havamall.com/wp-content/uploads/2019/12/image_2019_12_09T09_35_47_632Z.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>38,
                'name'=>'Đậu Đũa',
                'gardenName'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>'40.000 đồng',
                'weight'=>'1 kg',
                'category'=>'rau',
                'thumbnail'=>'https://csfood.vn/wp-content/uploads/2020/04/%C4%90%E1%BA%ADu-%C4%90%C5%A9a-VietRAT-T%C3%BAi-1kg.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>39,
                'name'=>'Củ Hẹ',
                'gardenName'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>'50.000 đồng',
                'weight'=>'1 kg',
                'category'=>'củ',
                'thumbnail'=>'https://www.collinsdictionary.com/images/full/shallot_6435766.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>40,
                'name'=>'Rau Nhút',
                'gardenName'=>'Trang trại hữu cơ BIOPHAP farm',
                'price'=>'35.000 đồng',
                'weight'=>'1 kg',
                'category'=>'rau',
                'thumbnail'=>'https://cdn.myshoptet.com/usr/www.vegandfood.com/user/shop/big/2554_water-mimosa.png?60fece6c',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>41,
                'name'=>'Mướp',
                'gardenName'=>'Nông trại hữu cơ Viễn Phú',
                'price'=>'27.500 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://csfood.vn/wp-content/uploads/2018/03/M%C6%B0%E1%BB%9Bp-Vietrat....png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>42,
                'name'=>'Củ Riềng',
                'gardenName'=>'Nông trại hữu cơ Viễn Phú',
                'price'=>'15.000 đồng',
                'weight'=>'1 kg',
                'category'=>'củ',
                'thumbnail'=>'https://m.soibien.vn/media/img/product/365/03/curieng_9471588761734.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>43,
                'name'=>'Mía',
                'gardenName'=>'Nông trại hữu cơ Viễn Phú',
                'price'=>'1.000 đồng',
                'weight'=>'1 kg',
                'category'=>'rau',
                'thumbnail'=>'https://www.mabu.vn/wp-content/uploads/2016/08/cay-mia.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>44,
                'name'=>'Đậu Bắp',
                'gardenName'=>'Nông trại hữu cơ Viễn Phú',
                'price'=>'20.000 đồng',
                'weight'=>'1 kg',
                'category'=>'rau',
                'thumbnail'=>'https://salt.tikicdn.com/cache/w1200/ts/product/7b/cb/5f/9834fbe63f28655489f7e2aef21e9ccc.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>45,
                'name'=>'Tía Tô',
                'gardenName'=>'Nông trại hữu cơ Viễn Phú',
                'price'=>'50.000 đồng',
                'weight'=>'1 kg',
                'category'=>'rau',
                'thumbnail'=>'https://dungcunongnghiep.vn/files/sanpham/855/1/jpg/tia-to-la-do.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>46,
                'name'=>'Quất',
                'gardenName'=>'Nông trại hữu cơ Viễn Phú',
                'price'=>'35.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://cdn.tgdd.vn/Products/Images/8786/232812/bhx/tac-trai-tui-300g-202012282304414517.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>47,
                'name'=>'Mít',
                'gardenName'=>'Nông trại hữu cơ Viễn Phú',
                'price'=>'30.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://sanvatphuongnam.vn/image/cache/catalog/products/tien-giang/mit-thai-cai-be-2-800x800.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>48,
                'name'=>'Sầu Riêng',
                'gardenName'=>'Nông trại hữu cơ Viễn Phú',
                'price'=>'65.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://lanhtaychan.com/sau-rieng-mui.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>49,
                'name'=>'Chanh Vàng',
                'gardenName'=>'Nông trại hữu cơ Viễn Phú',
                'price'=>'60.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://bizweb.dktcdn.net/thumb/1024x1024/100/372/252/products/chanh-vang.jpg?v=1594033185967',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>50,
                'name'=>'Chanh Xanh',
                'gardenName'=>'Nông trại hữu cơ Viễn Phú',
                'price'=>'15.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://choviet.co.uk/wp-content/uploads/2020/08/Chanh-xanh-1.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>51,
                'name'=>'Mận',
                'gardenName'=>'Nông trại hữu cơ Viễn Phú',
                'price'=>'20.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://m.soibien.vn/media/img/product/365/03/Thi%E1%BA%BFt%20k%E1%BA%BF%20kh%C3%B4ng%20t%C3%AAn%20-%202021-01-19T085352_7f21611019167.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>52,
                'name'=>'Anh Đào',
                'gardenName'=>'Nông trại hữu cơ Viễn Phú',
                'price'=>'100.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://upload.wikimedia.org/wikipedia/commons/b/bb/Cherry_Stella444.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>53,
                'name'=>'Chôm Chôm',
                'gardenName'=>'Nông trại hữu cơ Viễn Phú',
                'price'=>'40.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://chonongsankhanhhoa.vn/wp-content/uploads/2020/12/chom-chom-01.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>54,
                'name'=>'Dừa',
                'gardenName'=>'Nông trại hữu cơ Viễn Phú',
                'price'=>'40.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://cohafu.com/files/upload/products/dua-trai/dua-kho.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>55,
                'name'=>'Dưa',
                'gardenName'=>'Nông trại hữu cơ Viễn Phú',
                'price'=>'85.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://static.libertyprim.com/files/familles/melon-large.jpg?1574629891',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>56,
                'name'=>'Nhãn',
                'gardenName'=>'Nông trại hữu cơ Viễn Phú',
                'price'=>'85.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://lh3.googleusercontent.com/bcXx46BlhbpwCZMXfov_tW_BDIn6Cjml0Ue8IIfIz7JOiQ6AcimS_vMSRXayv4TVerCE3I5Hi1vLIYM6H9mVCxXt-ZOM=w600',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>57,
                'name'=>'Quýt',
                'gardenName'=>'Nông trại hữu cơ Viễn Phú',
                'price'=>'27.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://sc04.alicdn.com/kf/Uc3fba8d56ae34c0eae46b06c4a5c55d4J.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>58,
                'name'=>'Dâu Tây',
                'gardenName'=>'Nông trại hữu cơ Viễn Phú',
                'price'=>'100.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://dalatfarm.net/wp-content/uploads/2021/04/dau-tay-new-zealand-dalat-1.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>59,
                'name'=>'Mơ',
                'gardenName'=>'Nông trại hữu cơ Viễn Phú',
                'price'=>'32.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://bizweb.dktcdn.net/thumb/1024x1024/100/289/874/products/apricot-kernel-oil.jpg?v=1558872343457',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>60,
                'name'=>'Măng Cụt',
                'gardenName'=>'Nông trại hữu cơ Viễn Phú',
                'price'=>'35.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://organicfood.vn/image/cache/catalog/Trai-cay-huu-co/trai-cay-Viet-Nam/mang-cut-huu-co-600x450.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>61,
                'name'=>'Mãng Cầu Xiêm',
                'gardenName'=>'Công ty cổ phần Deli Fresh',
                'price'=>'18.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://freshfruitvietnam.vn/upload/images/2020/04/331x331-1586345269-single_product1-1.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>62,
                'name'=>'Hồng',
                'gardenName'=>'Công ty cổ phần Deli Fresh',
                'price'=>'60.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://dalatfarm.net/wp-content/uploads/2020/12/qua-hong-gion-1-1.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>63,
                'name'=>'Hồng Xiêm',
                'gardenName'=>'Công ty cổ phần Deli Fresh',
                'price'=>'37.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://cdn.shopify.com/s/files/1/0017/9234/4153/products/kalpatti-250x250_600x.jpg?v=1562951606',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>64,
                'name'=>'Cóc',
                'gardenName'=>'Công ty cổ phần Deli Fresh',
                'price'=>'25.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://choviet.co.uk/wp-content/uploads/2020/08/Coc-1.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>65,
                'name'=>'Mâm Xôi Đen',
                'gardenName'=>'Công ty cổ phần Deli Fresh',
                'price'=>'1.000.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://file.hstatic.net/1000378173/article/blackberry-1_45af4802e92a4451a69ce14ead681ca8_master.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>66,
                'name'=>'Mâm Xôi Đỏ',
                'gardenName'=>'Công ty cổ phần Deli Fresh',
                'price'=>'400.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://suckhoedoisong.qltns.mediacdn.vn/Images/bichvan/2016/10/29/loi-ich-suc-khoe-cua-qua-mam-xoi.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>67,
                'name'=>'Mướp Đắng',
                'gardenName'=>'Công ty cổ phần Deli Fresh',
                'price'=>'180.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://minhcaumart.vn/media/com_eshop/products/2900054.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>68,
                'name'=>'Quả Hạnh',
                'gardenName'=>'Công ty cổ phần Deli Fresh',
                'price'=>'400.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'http://blogcaycanh.vn/files/large/543ea4da6f67f2a',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>69,
                'name'=>'Rau Ngót',
                'gardenName'=>'Công ty cổ phần Deli Fresh',
                'price'=>'19.000 đồng',
                'weight'=>'1 kg',
                'category'=>'rau',
                'thumbnail'=>'https://minhcaumart.vn/media/com_eshop/products/RAUNGOT.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>70,
                'name'=>'Mướp Rừng',
                'gardenName'=>'Công ty cổ phần Deli Fresh',
                'price'=>'25.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://csfood.vn/wp-content/uploads/2018/03/M%C6%B0%E1%BB%9Bp-Vietrat....png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>71,
                'name'=>'Vải Thiều',
                'gardenName'=>'Công ty cổ phần Deli Fresh',
                'price'=>'30.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://suckhoedoisong.qltns.mediacdn.vn/2014/dsadsdsa-dfd66.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>72,
                'name'=>'Lê',
                'gardenName'=>'Công ty cổ phần Deli Fresh',
                'price'=>'100.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://vnn-imgs-f.vgcloud.vn/2019/04/26/12/tuyet-chieu-chon-le-chuan.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>73,
                'name'=>'Củ Cải',
                'gardenName'=>'Công ty cổ phần Deli Fresh',
                'price'=>'20.000 đồng',
                'weight'=>'1 kg',
                'category'=>'củ',
                'thumbnail'=>'https://static.ubofood.vn/images/cu-cai-trang-500g-03080080302_1000_750_51c0b935-3032-4df6-bda2-6178f14740b6.JPEG',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>74,
                'name'=>'Táo Mỹ',
                'gardenName'=>'Công ty cổ phần Deli Fresh',
                'price'=>'90.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'http://ninhco.com/uploads/images/tao-red-delicious-my.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>75,
                'name'=>'Táo Việt Nam',
                'gardenName'=>'Công ty cổ phần Deli Fresh',
                'price'=>'35.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://okdeal.vn/wp-content/uploads/2020/02/5d09ade165a91.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>76,
                'name'=>'Lựu',
                'gardenName'=>'Công ty cổ phần Deli Fresh',
                'price'=>'349.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://login.medlatec.vn//ckfinder/userfiles/images/an-luu-co-vo-sinh-khong-1.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>77,
                'name'=>'Gừng',
                'gardenName'=>'Công ty cổ phần Deli Fresh',
                'price'=>'60.000 đồng',
                'weight'=>'1 kg',
                'category'=>'củ',
                'thumbnail'=>'https://chuyeneva.vn/wp-content/uploads/2020/07/dau-bung-kinh-co-nen-uong-nuoc-gung-khong.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>78,
                'name'=>'Dưa Hấu',
                'gardenName'=>'Công ty cổ phần Deli Fresh',
                'price'=>'16.800 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://eminhatban.vn/img/uploads/images/Phuong/dau-hau.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>79,
                'name'=>'Xoài',
                'gardenName'=>'Công ty cổ phần Deli Fresh',
                'price'=>'40.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'http://pgrvietnam.org.vn/wp-content/uploads/2018/03/nhung-luu-y-khi-ap-dung-cach-lam-dep-tu-xoai-ma-it-nguoi-biet.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>80,
                'name'=>'Thanh Long Ruột Trắng',
                'gardenName'=>'Công ty cổ phần Deli Fresh',
                'price'=>'15.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://lh3.googleusercontent.com/proxy/glq044IbZIqN4QUYgTtsy04LPRWhOY8xhbTTlnZVVRazCxCqmD4uM7wLFcBNjNV1rhI3o5RkTVxtKlEfWVDPiOYc6cNAmlml7jWKNvWF4bNqxRSIYpPjbi_ylCi5TiGXr_gcy5Dm_rf57CIT',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>81,
                'name'=>'Thanh Long Ruột Đỏ',
                'gardenName'=>'Công Ty TNHH Lion Golden',
                'price'=>'20.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://cf.shopee.vn/file/9e8ee39b4ae4d06d76de2d3286202805',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>82,
                'name'=>'Đu Đủ',
                'gardenName'=>'Công Ty TNHH Lion Golden',
                'price'=>'15.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://hatgiongdalat.com/asset/upload/image/medium/du-du-ruot-do.jpg?v=20190410',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>83,
                'name'=>'Bơ Sáp',
                'gardenName'=>'Công Ty TNHH Lion Golden',
                'price'=>'20.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://dalatfarm.net/wp-content/uploads/2020/12/qua-bo-3-1-100x100.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>84,
                'name'=>'Chanh Leo',
                'gardenName'=>'Công Ty TNHH Lion Golden',
                'price'=>'15.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://media.cooky.vn/images/blog-2016/bat-mi-cong-dung-lam-dep-toan-dien-cua-chanh-day-1.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>85,
                'name'=>'Roi Đỏ',
                'gardenName'=>'Công Ty TNHH Lion Golden',
                'price'=>'68.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'http://bizweb.dktcdn.net/thumb/grande/100/413/256/products/roi-do.jpg?v=1610180488573',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>86,
                'name'=>'Ổi',
                'gardenName'=>'Công Ty TNHH Lion Golden',
                'price'=>'10.500 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://vtv1.mediacdn.vn/thumb_w/800/2018/10/9/qua-oi-xanh-chuan-crop-15390767439471555931383.jpeg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>87,
                'name'=>'Mít',
                'gardenName'=>'Công Ty TNHH Lion Golden',
                'price'=>'30.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'http://khamsuckhoedinhky.com.vn/wp-content/uploads/2018/07/loi-ich-va-tac-hai-cua-mit-doi-voi-suc-khoe-2.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>88,
                'name'=>'Ngô',
                'gardenName'=>'Công Ty TNHH Lion Golden',
                'price'=>'5.500 đồng',
                'weight'=>'1 kg',
                'category'=>'rau',
                'thumbnail'=>'https://minhcaumart.vn/media/com_eshop/products/NGONGOT.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>89,
                'name'=>'Dứa',
                'gardenName'=>'Công Ty TNHH Lion Golden',
                'price'=>'29.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://suckhoedoisong.qltns.mediacdn.vn/Images/thanhloan/2016/06/26/tac-dung-chua-benh-it-biet-cua-qua-dua-1.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>90,
                'name'=>'Hành Tây',
                'gardenName'=>'Công Ty TNHH Lion Golden',
                'price'=>'21.800 đồng',
                'weight'=>'1 kg',
                'category'=>'củ',
                'thumbnail'=>'https://media-cdn.laodong.vn/storage/newsportal/2019/11/14/766121/Tac-Dung-Hanh-Onion.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>91,
                'name'=>'Cà Tím',
                'gardenName'=>'Công Ty TNHH Lion Golden',
                'price'=>'20.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://thucphamdongxanh.com/wp-content/uploads/2019/09/ca-tim-ngon.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>92,
                'name'=>'Kiwi Xanh',
                'gardenName'=>'Công Ty TNHH Lion Golden',
                'price'=>'130.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://hinh365.com/wp-content/uploads/2020/06/8847fdba3e2eeef45684084618041002.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>93,
                'name'=>'Kiwi Vàng',
                'gardenName'=>'Công Ty TNHH Lion Golden',
                'price'=>'200.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://m.soibien.vn/media/img/product/365/03/Untitled-1_0c71601969903-min_4791609751782.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>94,
                'name'=>'Súp Lơ',
                'gardenName'=>'Công Ty TNHH Lion Golden',
                'price'=>'45.000 đồng',
                'weight'=>'1 kg',
                'category'=>'rau',
                'thumbnail'=>'https://vuonbabylon.vn/wp-content/uploads/2021/01/bong-cai-xanh-vuon-babylon.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>95,
                'name'=>'Nho',
                'gardenName'=>'Công Ty TNHH Lion Golden',
                'price'=>'40.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://thuviendohoa.vn/upload/images/items/hinh-anh-chum-nho-tim-tuoi-ngon-png-59-59.webp',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>96,
                'name'=>'Đậu Hà Lan',
                'gardenName'=>'Công Ty TNHH Lion Golden',
                'price'=>'80.000 đồng',
                'weight'=>'1 kg',
                'category'=>'rau',
                'thumbnail'=>'https://dalatfarm.net/wp-content/uploads/2021/06/hat-dau-ha-lan.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>97,
                'name'=>'Na',
                'gardenName'=>'Công Ty TNHH Lion Golden',
                'price'=>'50.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://vinmec-prod.s3.amazonaws.com/images/20200505_140634_080820_dau-da-day-co-nen-a.max-1800x1800.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>98,
                'name'=>'Cà Rốt',
                'gardenName'=>'Công Ty TNHH Lion Golden',
                'price'=>'17.000 đồng',
                'weight'=>'1 kg',
                'category'=>'củ',
                'thumbnail'=>'https://bhfood.vn/wp-content/uploads/2020/04/caCC80-roCC82CC81t.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>99,
                'name'=>'Cà Chua',
                'gardenName'=>'Công Ty TNHH Lion Golden',
                'price'=>'30.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://orfarm.com.vn/images/products/2020/07/11/original/27_f102291_rau_muong_3962a35b44254dcda56c59ebc01f7594_large_1594445009.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>100,
                'name'=>'Cà Pháo',
                'gardenName'=>'Công Ty TNHH Lion Golden',
                'price'=>'40.000 đồng',
                'weight'=>'1 kg',
                'category'=>'quả',
                'thumbnail'=>'https://photo-cms-anninhthudo.zadn.vn/w600/Uploaded/2021/206/2020_05_04/loi-ich.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
